# Night Lighting ##################################################

- id: night_light
  alias: Night Light
  hide_entity: true
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  action:
  - service: homeassistant.turn_on
    entity_id: light.gateway_light_f0b429b41630
    data:
      rgb_color:
      - 255
      - 100
      - 0
  - service: homeassistant.turn_on
    entity_id: light.lightstrip
    data:
      rgb_color:
      - 255
      - 100
      - 0
- id: night_light_off
  alias: Night Light Off
  hide_entity: true
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:30:00
  action:
  - service: homeassistant.turn_off
    entity_id: light.gateway_light_f0b429b41630
  - service: homeassistant.turn_off
    entity_id: light.lightstrip

# Manual Light Control ##################################################

- id: kitchenlighttoggle
  alias: Kitchen Light Toggle
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d00010f436b
    event_type: xiaomi_aqara.click
    platform: event
  action:
  - data:
      entity_id: light.kitchen_lights
    service: light.toggle
- id: kitchenlightsethome
  alias: Kitchen Light Set Home
  trigger:
  - event_data:
      click_type: double
      entity_id: binary_sensor.switch_158d00010f436b
    event_type: xiaomi_aqara.click
    platform: event
  action:
    - data:
        entity_id: light.kitchen_lights
        rgb_color:
        - 255
        - 183
        - 123
      service: light.turn_on
- id: bedroomlighttoggle
  alias: Bedroom Light Toggle
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001146391
      click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: light.bedroom_lights
- id: bedroomlightsethome
  alias: Bedroom Light Set Home
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001146391
        click_type: double
  action:
    - service: light.turn_on
      data:
        entity_id: light.bedroom_lights
        brightness: 204
        rgb_color:
        - 255
        - 183
        - 123
- id: bedroomlightred
  alias: Bedroom Light Set Red
  trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001146391
      click_type: long_click_press
  action:
  - service: light.turn_on
    data:
      entity_id: light.bedroom_lights
      brightness: 255
      rgb_color:
      - 255
      - 0
      - 0

# Kids Radiator ##################################################

- id: radiator_kids_off
  alias: Kids radiator  Off
  hide_entity: true
  trigger:
  - platform: time
    at: '6:00:00'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.kidsradiator


# Alarm Automations ##################################################

- id: triggeralarm
  alias: TriggerAlarm
  hide_entity: true
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000104babc
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d00014dc2a4
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d000130cd9a
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.homealarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.homealarm
- id: disarm_alarm
  alias: Disarm Alarm
  trigger:
  - entity_id: sensor.mainpeople_status
    platform: state
    to: Just Arrived
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.homealarm
- id: alarm_triggered
  alias: Alarm Triggered
  trigger:
    platform: state
    entity_id: alarm_control_panel.homealarm
    to: triggered
  action:
  - service: notify.nir
    data:
      message: Alarm Triggered
      title: Security Message
- id: arm_alarm
  alias: Arm Alarm
  trigger:
  - entity_id: sensor.mainpeople_status
    # for:
    #   minutes: 5
    platform: state
    to: Away
  action:
  - service: notify.nir
    data:
      message: Arming Alarm
      title: Security Message
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.homealarm
    
# Washing Machine Automations ##################################################
- id: washingmachinedone
  alias: Washing Machine Done
  trigger:
  - entity_id: sensor.washingmachine_status
    for:
      minutes: 12
    platform: state
    to: Idle
    from: Working
  action:
  - service: notify.everyone
    data:
      message: Washing Machine Finished
      title: Laundry Alert

# Prescence Automations ##################################################

- id: markpersonarrived
  alias: Mark person as just arrived
  trigger:
    - platform: state
      entity_id: group.nir_presence
      from: 'not_home'
      to: 'home'
    - platform: state
      entity_id: group.moran_presence
      from: 'not_home'
      to: 'home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.nir_presence' %}
            input_select.nir_status_dropdown
          {% else %}
            input_select.moran_status_dropdown
          {% endif %}
        option: >
          {% if trigger.entity_id == 'group.nir_presence' %}
            {% if states.input_select.nir_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% else %}
            {% if states.input_select.moran_status_dropdown.state == 'Just Left' %}
              Home
            {% else %}
              Just Arrived
            {% endif %}
          {% endif %}

- id: markpersonhome
  alias: Mark person as home
  trigger:
    - platform: state
      entity_id: input_select.nir_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.moran_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.nir_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.moran_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.nir_status_dropdown' %}
            input_select.nir_status_dropdown
          {% else %}
            input_select.moran_status_dropdown
          {% endif %}
        option: Home

- id: markpersonjustleft
  alias: Mark person as just left
  trigger:
    - platform: state
      entity_id: group.nir_presence
      from: 'home'
      to: 'not_home'
    - platform: state
      entity_id: group.moran_presence
      from: 'home'
      to: 'not_home'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'group.nir_presence' %}
            input_select.nir_status_dropdown
          {% else %}
            input_select.moran_status_dropdown
          {% endif %}
        option: Just Left

- id: markpersonaway
  alias: Mark person as away
  trigger:
    - platform: state
      entity_id: input_select.nir_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
    - platform: state
      entity_id: input_select.moran_status_dropdown
      to: 'Just Left'
      for:
        minutes: 10
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.nir_status_dropdown' %}
            input_select.nir_status_dropdown
          {% else %}
            input_select.moran_status_dropdown
          {% endif %}
        option: Away

- id: markpersonextendedaway
  alias: Mark person as extended away
  trigger:
    - platform: state
      entity_id: input_select.nir_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.moran_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.nir_status_dropdown' %}
            input_select.nir_status_dropdown
          {% else %}
            input_select.moran_status_dropdown
          {% endif %}
        option: Extended Away

# - id: WelcomeHomeNir
#   alias: Welcome Home Greeting Nir
#   trigger:
#     - platform: state
#       entity_id: sensor.nir_status
#       to: 'Just Arrived'
#   condition:
#       - condition: or
#         conditions:
#           - condition: state
#             entity_id: sensor.moran_status
#             state: 'Away'
#           - condition: state
#             entity_id: sensor.moran_status
#             state: 'Just Left'
#           - condition: state
#             entity_id: sensor.moran_status
#             state: 'Extended Away'
#       - condition: time
#         after: '07:00:00'
#         before: '21:00:00'      
#   action:  
#     - service: media_player.turn_on
#       entity_id: media_player.living_room_speaker
#     - service: media_player.volume_set
#       entity_id: media_player.living_room_speaker
#       data:
#         volume_level: 0.5
#     - service: tts.google_say
#       entity_id: media_player.living_room_speaker
#       data:
#         message: 'Welcome Home Nir'

# - id: WelcomeHomeMoran
#   alias: Welcome Home Greeting Moran
#   trigger:
#     - platform: state
#       entity_id: sensor.moran_status
#       to: 'Just Arrived'
#   condition:
#       - condition: or
#         conditions:
#           - condition: state
#             entity_id: sensor.nir_status
#             state: 'Away'
#           - condition: state
#             entity_id: sensor.nir_status
#             state: 'Just Left'
#           - condition: state
#             entity_id: sensor.nir_status
#             state: 'Extended Away'
#       - condition: time
#         after: '07:00:00'
#         before: '21:00:00'      
#   action:  
#     - service: media_player.turn_on
#       entity_id: media_player.living_room_speaker
#     - service: media_player.volume_set
#       entity_id: media_player.living_room_speaker
#       data:
#         volume_level: 0.5
#     - service: tts.google_say
#       entity_id: media_player.living_room_speaker
#       data:
#         message: 'Welcome Home Moran'
