- id: night_light
  alias: Night Light
  hide_entity: true
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  action:
  - service: homeassistant.turn_on
    entity_id: light.gateway_light_f0b429b41630
    data:
      rgb_color:
      - 255
      - 100
      - 0
  - service: homeassistant.turn_on
    entity_id: light.lightstrip
    data:
      rgb_color:
      - 255
      - 100
      - 0
- id: night_light_off
  alias: Night Light Off
  hide_entity: true
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:30:00
  action:
  - service: homeassistant.turn_off
    entity_id: light.gateway_light_f0b429b41630
  - service: homeassistant.turn_off
    entity_id: light.lightstrip
- id: kitchenlighttoggle
  alias: Kitchen Light Toggle
  trigger:
  - event_data:
      click_type: single
      entity_id: binary_sensor.switch_158d00010f436b
    event_type: click
    platform: event
  action:
  - data:
      entity_id: light.kitchen_lights
    service: light.toggle
- id: bedroomlighttoggle
  alias: Bedroom Light Toggle
  trigger:
  - platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001146391
      click_type: single
  action:
  - service: light.toggle
    data:
      entity_id: group.bedroom
- id: triggeralarm
  alias: TriggerAlarm
  hide_entity: true
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000104babc
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d00014dc2a4
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d000130cd9a
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: alarm_control_panel.homealarm
    state: armed_away
  action:
  - service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.homealarm
- id: disarm_alarm
  alias: Disarm Alarm
  trigger:
  - entity_id: device_tracker.nirs_pixels_pixel
    platform: state
    to: home
  - entity_id: device_tracker.morans_phone
    platform: state
    to: home
  action:
    service: alarm_control_panel.alarm_disarm
    data:
      entity_id: alarm_control_panel.homealarm
- id: alarm_triggered
  alias: Alarm Triggered
  trigger:
    platform: state
    entity_id: alarm_control_panel.homealarm
    to: triggered
  action:
  - service: notify.pushover
    data:
      message: Alarm Triggered
      title: Security Message
- id: arm_alarm
  alias: Arm Alarm
  trigger:
  - entity_id: group.homepeople
    for:
      minutes: 5
    platform: state
    to: not_home
  action:
  - data:
      message: Arming Alarm
      title: Security Message
    service: notify.pushover
  - entity_id: alarm_control_panel.homealarm
    service: alarm_control_panel.alarm_arm_away

# Presence

# - id: markpersonarrived
#   alias: Mark person as just arrived
#   trigger:
#     - platform: state
#       entity_id: device_tracker.nirs_pixels_pixel
#       from: 'not_home'
#       to: 'home'
#     - platform: state
#       entity_id: device_tracker.morans_phone
#       from: 'not_home'
#       to: 'home'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'device_tracker.nirs_pixels_pixel' %}
#             input_select.nir_status_dropdown
#           {% else %}
#             input_select.moran_status_dropdown
#           {% endif %}
#         option: >
#           {% if trigger.entity_id == 'device_tracker.nirs_pixels_pixel' %}
#             {% if states.input_select.nir_status_dropdown.state == 'Just Left' %}
#               Home
#             {% else %}
#               Just Arrived
#             {% endif %}
#           {% else %}
#             {% if states.input_select.moran_status_dropdown.state == 'Just Left' %}
#               Home
#             {% else %}
#               Just Arrived
#             {% endif %}
#           {% endif %}

# - id: markpersonhome
#   alias: Mark person as home
#   trigger:
#     - platform: state
#       entity_id: input_select.nir_status_dropdown
#       to: 'Just Arrived'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.moran_status_dropdown
#       to: 'Just Arrived'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.nir_status_dropdown
#       from: 'Just Left'
#       to: 'Just Arrived'
#     - platform: state
#       entity_id: input_select.moran_status_dropdown
#       from: 'Just Left'
#       to: 'Just Arrived'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'input_select.nir_status_dropdown' %}
#             input_select.nir_status_dropdown
#           {% else %}
#             input_select.moran_status_dropdown
#           {% endif %}
#         option: Home

# - id: markpersonjustleft
#   alias: Mark person as just left
#   trigger:
#     - platform: state
#       entity_id: device_tracker.nirs_pixel
#       from: 'home'
#       to: 'not_home'
#     - platform: state
#       entity_id: device_tracker.morans_phone
#       from: 'home'
#       to: 'not_home'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'device_tracker.nirs_pixel' %}
#             input_select.nir_status_dropdown
#           {% else %}
#             input_select.moran_status_dropdown
#           {% endif %}
#         option: Just Left

# - id: markpersonaway
#   alias: Mark person as away
#   trigger:
#     - platform: state
#       entity_id: input_select.nir_status_dropdown
#       to: 'Just Left'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.moran_status_dropdown
#       to: 'Just Left'
#       for:
#         minutes: 10
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'input_select.nir_status_dropdown' %}
#             input_select.nir_status_dropdown
#           {% else %}
#             input_select.moran_status_dropdown
#           {% endif %}
#         option: Away

# - id: markpersonextendedaway
#   alias: Mark person as extended away
#   trigger:
#     - platform: state
#       entity_id: input_select.nir_status_dropdown
#       to: 'Away'
#       for:
#         hours: 24
#     - platform: state
#       entity_id: input_select.moran_status_dropdown
#       to: 'Away'
#       for:
#         hours: 24
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'input_select.nir_status_dropdown' %}
#             input_select.nir_status_dropdown
#           {% else %}
#             input_select.moran_status_dropdown
#           {% endif %}
#         option: Extended Away

