name: Home
views:
    # The name of a view will be used as tab title..
    # Might be used for other things in the future.
  - name: Main
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    tab_icon: mdi:home-assistant
    # The cards to show on this view.
    cards:
      - type: picture-glance
        image: /local/livingroom.jpg
        title: Living Room
        entities:
          - binary_sensor.motion_sensor_158d00014dc2a4
          - binary_sensor.door_window_sensor_158d000104babc
          - binary_sensor.livingroom_tv
      - type: picture-glance
        title: Kitchen
        entities:
          - light.kitchen_lights
        state_image:
          "on": /local/kitchen.jpg
          "off": /local/kitchendark.jpg
        entity: light.kitchen_lights
      - type: picture-glance
        image: https://images.pexels.com/photos/356048/pexels-photo-356048.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
        title: Bedroom
        entities:
          - binary_sensor.motion_sensor_158d000130cd9a
          - light.bedroom_lights
      - type: entity-filter
        entities:
          - device_tracker.morans_phone
          - device_tracker.nirs_pixel
        state_filter:
        - 'home'
        card: 
          type: glance
          title: Who's home
      - type: entity-filter
        entities:
          - group.bedroomlights
          - light.gateway_light_f0b429b41630
          - light.lightstrip
          - group.kitchen
          - switch.printer
        state_filter:
          - 'on'
        card:
          title: Eating power
      - type: entities
        entities:
          - sensor.time
          - sensor.fastcom_download
          - sensor.google_wifi_uptime
          - switch.printer
          - alarm_control_panel.homealarm
      - type: conditional
        conditions:
          - entity: media_player.spotify
            state: "playing"
        card:
          type: media-control
          entity: media_player.spotify

