name: Home
views:
    # The name of a view will be used as tab title..
    # Might be used for other things in the future.
  - name: Main
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    theme: dark-mode
    tab_icon: mdi:home-assistant
    # The cards to show on this view.
    cards:
      - type: vertical-stack
        cards:
          - type: glance
            column_width: calc(100% / 3)
            entities:
              - sensor.time
              - entity: alarm_control_panel.homealarm
                name: Alarm
              - entity: sensor.fastcom_download
                name: D/L Speed
              - entity: sensor.google_wifi_uptime
                name: Router Up
              - entity: switch.printer
                tap_action: toggle
          - type: entity-filter
            entities:
              - group.nir_presence
              - group.moran_presence
            state_filter:
            - 'home'
            card: 
              type: glance
              title: Who's home
            show_empty: false
      - type: picture-glance
        image: /local/livingroom.jpg
        title: Living Room
        entities:
          - binary_sensor.motion_sensor_158d00014dc2a4
          - binary_sensor.door_window_sensor_158d000104babc
          - binary_sensor.mediacenter_pc
          - binary_sensor.xbox_one_x
          - binary_sensor.livingroom_tv
      - type: picture-entity
        title: Kitchen
        entities:
          - light.kitchen_lights
        state_image:
          "on": /local/kitchen.jpg
          "off": /local/kitchendark.jpg
        entity: light.kitchen_lights
        name: Kitchen Lights
        tap_action: toggle
      - type: picture-glance
        image: https://images.pexels.com/photos/356048/pexels-photo-356048.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=295&w=490
        title: Bedroom
        entities:
          - binary_sensor.motion_sensor_158d000130cd9a
          - binary_sensor.mi_box
          - light.bedroom_lights
      - type: entity-filter
        entities:
          - group.bedroomlights
          - light.gateway_light_f0b429b41630
          - light.lightstrip
          - group.kitchen
          - switch.printer
        state_filter:
          - 'on'
        card:
          title: Eating power
      - type: conditional
        conditions:
          - entity: media_player.spotify
            state: "playing"
        card:
          type: media-control
          entity: media_player.spotify

